---
- name: nginx.repo
  become: yes
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo

- name: install nginx
  become: yes
  yum:
    name: nginx
    state: latest

- name: start nginx
  become: yes
  service:
    name: nginx
    state: started
